name: antiquewebemquiry
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0
  intl: ^0.20.2
  quickalert: ^1.1.0
  awesome_dialog: ^3.2.1
  awesome_card: ^1.1.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  firebase_core: 2.24.2
  
  encrypt: ^5.0.3
  crypto: ^3.0.3
  logging: ^1.2.0
  logger: ^2.6.0
  firebase_messaging:
    path: my_plugins/firebase_messaging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Italic.ttf
          style: italic

flutter_native_splash:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
