// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3fDk9mBIQ_3RwEeVZJle8yltyw9Di8UY',
    appId: '1:120916304501:web:3d76a78327ee809a980e3c',
    messagingSenderId: '120916304501',
    projectId: 'aswebinquiry',
    authDomain: 'aswebinquiry.firebaseapp.com',
    storageBucket: 'aswebinquiry.firebasestorage.app',
    measurementId: 'G-F29PJXK20N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMJMfCiS6Q8FIF86IhwfvrkE6l8-bY5IE',
    appId: '1:120916304501:android:37f4cbd436d0d8fb980e3c',
    messagingSenderId: '120916304501',
    projectId: 'aswebinquiry',
    storageBucket: 'aswebinquiry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ukAqdVr6qL7ZDdibVidpnbohGxiXmK0',
    appId: '1:120916304501:ios:33845662d2633018980e3c',
    messagingSenderId: '120916304501',
    projectId: 'aswebinquiry',
    storageBucket: 'aswebinquiry.firebasestorage.app',
    iosBundleId: 'com.esoftsys.antiquesoftwebinquiry2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ukAqdVr6qL7ZDdibVidpnbohGxiXmK0',
    appId: '1:120916304501:ios:b0671e4710951a14980e3c',
    messagingSenderId: '120916304501',
    projectId: 'aswebinquiry',
    storageBucket: 'aswebinquiry.firebasestorage.app',
    iosBundleId: 'com.esoftsys.antiquesoftwebinquiry2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3fDk9mBIQ_3RwEeVZJle8yltyw9Di8UY',
    appId: '1:120916304501:web:26639ac03e245de6980e3c',
    messagingSenderId: '120916304501',
    projectId: 'aswebinquiry',
    authDomain: 'aswebinquiry.firebaseapp.com',
    storageBucket: 'aswebinquiry.firebasestorage.app',
    measurementId: 'G-VS3JQCG1TQ',
  );
}
